name: Init, validate, plan and apply VPC/EKS

on:
  push:
    branches: [ "main" ]
    
permissions:
  id-token: write # Needed for OIDC
  contents: write # Needed to push commits

env:
  AWS_REGION: us-east-1
  
jobs:
   build-and-push-ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::927749346049:role/github-actions-dev-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5" # Specify the version you want to use

      - name: Init and validate Terraform
        working-directory: ./terraform/vpc
        run: |
          terraform init
          terraform validate
          terraform plan
